app/profile/__init__.py
from flask import Blueprint


profile = Blueprint('profiles', __name__)

from . import routes

app/profile/routes.py
from . import profile
from flask_login import login_required, current_user
from app.models import User, Profile
from flask import render_template, current_app, flash, redirect, url_for
from sqlalchemy.orm import joinedload
from app.forms import EditProfileForm, FinishProfileForm
from app import csrf, db
import uuid, os
from werkzeug.utils import secure_filename
from .utils import SaveProfilePicture


@profile.route('/profile')
@login_required
def profile_info():
    return render_template('profile/profile.html')


@profile.route('/profile/edit', methods=['POST', 'GET'])
@login_required
@csrf.exempt
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        pro_pic = form.data.get('pro_pic')
        bio = form.data.get('bio')
        try:
            if pro_pic:
                save_pic_obj = SaveProfilePicture(current_app, current_user)
                current_user.profile_pic=save_pic_obj.save_profile_picture(pro_pic)
            if bio:
                current_user.user_bio=bio
            db.session.commit()
            flash('Your profile has been saved.')
            return redirect(url_for('profiles.profile_info'))
        except Exception as e:
            flash("Something Went wrong. Please try again! {0}".format(str(e)))
            return redirect(url_for('profiles.edit_profile'))

    return render_template('profile/edit_profile.html', form=form)

@profile.route('/profile/<int:user_id>')
@login_required
def user_profile(user_id):
    if user_id == current_user.id:
        return redirect(url_for('profiles.profile_info'))
    user = User.query.get_or_404(user_id)
    if user:
        return render_template('profile/user_profile.html', user=user)
    

@profile.route('/profile/finish', methods=['POST', 'GET'])
@login_required
@csrf.exempt # finish profile has a form
def finish_profile():
    return 

app/templates/profile/edit_profile.html
{% extends 'base.html' %}
{% block head %}
    <title>Edit Your Profile</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile-edit.css') }}">
{% endblock head %}
{% block content %}
    {% with err_msg=get_flashed_messages()  %}
    <ul>
        {% for error in err_msg %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endwith %}
    <div class="profile-edit-container">
        <h1 class="edit-heading">Edit Your Profile</h1>
        <form method='post' action="{{ url_for('profiles.edit_profile') }}" enctype="multipart/form-data" class="profile-edit-form">
            {{ form.csrf_token }}
            <p class="form-field">
                <label for="{{ form.pro_pic.id }}">Profile Picture:</label>
                {{ form.pro_pic }}
                {% for error in form.pro_pic.errors  %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>
            <p class="form-field">
                <label for="{{ form.bio.id }}">Bio:</label>
                {{ form.bio(placeholder='Your Bio goes here!') }}
                {% for error in form.bio.errors  %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>
            <p class="form-field">
                {{ form.add(value='Submit!', class='profile-edit-submit') }}
            </p>
        </form>
    </div>
{% endblock content %}

app/templates/profile/finish_profile.html
{% extends 'base.html' %}
{% block head %}
<title>Finish Profile</title>
<style>
  .container {
    width: 80%;
    margin: 0 auto;
    padding: 40px;
    background-color: #f5f5f5;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  h2 {
    text-align: center;
    color: #333;
    margin-bottom: 20px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  .form-label {
    display: block;
    font-weight: bold;
    margin-bottom: 5px;
    color: #555;
  }
  
  .form-control {
    width: 100%;
    padding: 12px;
    border: none;
    border-radius: 5px;
    background-color: #fff;
    font-size: 16px;
    color: #555;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    transition: box-shadow 0.3s ease;
  }
  
  .form-control:focus {
    outline: none;
    box-shadow: 0 0 5px rgba(66, 103, 178, 0.8);
  }
  
  #intrest {
    list-style-type: none;
  }
  
  .error {
    color: red;
    font-size: 14px;
  }
  
  .submit-button {
    text-align: center;
  }
  
  .form-check-label {
    color: #555;
    font-size: 14px;
    margin-left: 5px;
    text-decoration: none; /* Remove text decoration */
  }
  
  .form-check-input {
    width: 20px;
    height: 20px;
    margin-right: 10px;
    position: relative;
    top: 3px;
    vertical-align: middle;
  }
  
  .btn {
    display: inline-block;
    padding: 10px 20px;
    background-color: #4267B2;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    font-size: 16px;
    transition: background-color 0.3s ease;
  }
  
  .btn:hover {
    background-color: #405892;
  }
  
  @media screen and (max-width: 500px) {
    .container {
      max-width: 90%;
      padding: 30px;
    }
  }
</style>
{% endblock head %}

{% block content %}
{% with err_msg=get_flashed_messages()  %}
        {% if err_msg %}
        <ul>
            {% for msg in err_msg %}
                <li>{{ msg }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
<div class="container">
  <h2>Finish Profile</h2>
  <form method='post' action="{{ url_for('profiles.finish_profile') }}" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="form-group">
      <label class="form-label" for="{{ form.pro_pic.id_for_label }}">Profile Picture</label>
      {{ form.pro_pic(class="form-control") }}
      {% for error in form.pro_pic.errors %}
        <span class="error">{{ error }}</span>
      {% endfor %}
    </div>

    <div class="form-group">
      <label class="form-label" for="{{ form.bio.id_for_label }}">Bio</label>
      {{ form.bio(class="form-control") }}
      {% for error in form.bio.errors  %}
        <span class="error">{{ error }}</span>
      {% endfor %}
    </div>

    <div class="form-group">
      <label class="form-label" for="{{ form.interest.id_for_label }}">Interest</label>
      {{ form.interest(class="form-control", id="intrest") }}
      {% for error in form.interest.errors %}
        <span class="error">{{ error }}</span>
      {% endfor %}
    </div>

    <div class="form-group">
      <label class="form-label" for="{{ form.country.id_for_label }}">Country</label>
      {{ form.country(class="form-control") }}
      {% for error in form.country.errors %}
        <span class="error">{{ error }}</span>
      {% endfor %}
    </div>

    <div class="form-group">
      <label class="form-label" for="{{ form.birthday.id_for_label }}">Birthday</label>
      {{ form.birthday(placeholder="Birthday", class="form-control") }}
      {% for error in form.birthday.errors %}
        <span class="error">{{ error }}</span>
      {% endfor %}
    </div>

    <div class="form-group">
      <input type="checkbox" class="form-check-input" id="check" required>
      <label class="form-check-label" for="check">I agree to the terms and conditions</label>
    </div>

    <div class="submit-button">
      {{ form.finish(class="btn") }}
    </div>
  </form>
</div>
{% endblock content %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% block head %}
    <title>{{ current_user.username }}'s profile</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
{% endblock  %}
{% block content %}
    <div class="profile-container">
        <div class="profile-header">
            {% if current_user.profile_pic %}
            <a href="{{ url_for('profiles.edit_profile') }}">
                <img class="profile-pic" src="{{ url_for('static', filename='data/'+ current_user.email + '/' + current_user.profile_pic) }}">
            </a>
            {% else %}
            <a href="{{ url_for('profiles.edit_profile') }}">
                <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
            </a>
            {% endif %}
            <h1 class="profile-name">{{ current_user.username }} {{ current_user.last_name }}</h1>
            <p class="profile-email">{{ current_user.email }}</p>
        </div>
        <div class="profile-content">
            <div class="profile-info">
                <div class="profile-info-item">
                    <span class="info-label">Birthday:</span>
                    <span class="info-value">{{ current_user.birthday }}</span>
                    <span class="info-label">Country:</span>
                    <span class="info-value">{{ current_user.country }}</span>
                </div>
                {% if current_user.user_bio  %}
                <div class="profile-info-item">
                    <span class="info-label">Bio:</span>
                    <span class="info-value">{{ current_user.user_bio }}</span>
                </div>
                {% else %}
                <a href="{{ url_for('profiles.edit_profile') }}" class="profile-bio-link">Tell us something about you!</a>
                {% endif %}
            </div>
            <div class="profile-actions">
                <a href="{{ url_for('profiles.edit_profile') }}" class="profile-action-btn">Edit Profile</a>
                <a href="{{ url_for('auth.logout') }}" class="profile-action-btn">Logout</a>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/profile/user_profile.html
{% extends 'base.html' %}
{% block head %}
    <title>{{ user.username }}'s profile</title>
    
{% endblock  %}
{% block content %}
    <div class="profile-container">
        <div class="profile-header">
            {% if user.profile_pic %}
                {% if current_user.id == user.id %}
                    <a href="{{ url_for('profiles.edit_profile') }}">
                        <img class="profile-pic" src="{{ url_for('static', filename='data/'+ user.email + '/' + user.profile_pic) }}">
                    </a>   
                {% else %}
                <img class="profile-pic" src="{{ url_for('static', filename='data/'+ user.email + '/' + user.profile_pic) }}">
                {% endif %}
            {% else %}
                {% if current_user.id == user.id %}
                    <a href="{{ url_for('profiles.edit_profile') }}">
                        <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
                    </a>
                {% else %}
                <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
                {% endif %}
            {% endif %}
            <h1 class="profile-name">{{ user.username }} {{ user.last_name }}</h1>
            <p class="profile-email">{{ user.email }}</p>
        </div>
        <div class="profile-content">
            <div class="profile-info">
                <div class="profile-info-item">
                    <span class="info-label">Birthday:</span>
                    <span class="info-value">{{ user.birthday }}</span>
                </div>
                {% if user.user_bio  %}
                <div class="profile-info-item">
                    <span class="info-label">Bio:</span>
                    <span class="info-value">{{ user.user_bio }}</span>
                </div>
                {% else %}
                <div class="profile-info-item">
                    <span class="info-label">Bio:</span>
                    <span class="info-value">...</span>
                </div>
                {% endif %}
            </div>
            <div class="profile-actions">
                {% if user in current_user.friends %}
                    <a href="{{ url_for('friend.delete_friend', friend_id=user.id) }}" class="profile-action-btn">Unfriend</a>
                    <a href="#" class="profile-action-btn">Message</a>
                {% else %}
                    <a href="{{ url_for('friend.send_friend_request', friend_id=user.id) }}" class="profile-action-btn">Add Friend</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}