app/posts/__init__.py
from flask import Blueprint

post = Blueprint('post', __name__)
from . import routes

app/posts/routes.py
from . import post
from flask import render_template, redirect, url_for, request, current_app, flash, session, abort
from app.models import Post, Like, Comment, User
from app.forms import CreatePostForm, CreateCommentForm, UpdatePostForm
from flask_login import current_user, login_required
import os 
from werkzeug.utils import secure_filename
from .utils import allowed_file, PostUpdater
from app import db, csrf
import uuid
from sqlalchemy.orm import joinedload

@post.route('/post', methods=['POST', 'GET'])
@login_required
@csrf.exempt
def create_post():
    form = CreatePostForm()
    if form.validate_on_submit():
        content = form.content.data
        image = form.data.get('image')
        
        if image and allowed_file(image.filename):
            uuid1_value = uuid.uuid1()
            img_name = str(uuid1_value) + secure_filename(image.filename) 
            try:
                path = os.path.join(current_app.config['UPLOAD_FOLDER'], current_user.email, "post_images", img_name)
                post = Post(user_id=current_user.id, content=content, post_img=os.path.join('post_images', img_name))
                db.session.add(post)
                db.session.commit()
                image.save(path)
            except Exception as e:
                flash('Something went wrong. Please try again! Error: ' + str(e))
                return redirect(url_for('post.create_post'))
                
            flash('Your post has been added successfully!')
            return redirect(url_for('main.home'))

        post = Post(user_id=current_user.id, content=content)
        db.session.add(post)
        db.session.commit()

        flash('Your post has been added successfully!')
        return redirect(url_for('main.home'))

    return render_template('post/create_post.html', form=form)
@post.route('/detail/<int:post_id>')
@login_required
def detail_post_view(post_id):
    form = CreateCommentForm()
    post = Post.query.get_or_404(post_id)
    if post:
        post = (
            Post.query
            .options(joinedload(Post.user))
            .filter(Post.id == post_id)
            .first()
        )
        comments = (
            Comment.query
            .join(User)
            .filter(Comment.post_id == post_id)
            .all()
        )
        likes = (
            Like.query
            .join(User)
            .filter(Like.post_id == post_id)
            .all()
        )
        return render_template('post/post_detail.html', post=post, comments=comments, likes=likes, form=form)
    
@post.route('/comment/<int:post_id>', methods=['POST'])
@csrf.exempt
@login_required
def comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post:
        content = request.form.get("content")
        comment = Comment(user_id=current_user.id, post_id=post.id, content=content)
        try:
            db.session.add(comment)
            db.session.commit()
        except Exception as e:
            flash('Error {0}'.format(str(e)))
            return redirect(url_for('post.detail_post_view', post_id=post.id))
        
        return redirect(url_for('post.detail_post_view', post_id=post.id))
    
@post.route('/like/<int:post_id>')
@login_required
def like_post_view(post_id):
    post =  Post.query.get_or_404(post_id)
    if post:
        if like := Like.query.filter_by(user_id=current_user.id, post_id=post.id).first():
            db.session.delete(like)
            db.session.commit()
            return redirect(url_for('main.home'))
        like = Like(user_id=current_user.id, post_id=post.id)
        db.session.add(like)
        db.session.commit()
        return redirect(url_for('main.home'))
        
@post.route('/update/<int:post_id>', methods=['GET', 'POST'])
@csrf.exempt
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = UpdatePostForm()

    if form.validate_on_submit():
        if session.get('_csrf_token') != request.form.get('_csrf_token'):
            return abort(400, 'Invalid CSRF Token')

        try:
            updater = PostUpdater(current_app, current_user)            
            updater.update_post_fields(post, form)
            db.session.commit()
            return redirect(url_for('main.home'))
        except Exception as e:
            db.session.rollback()
            flash('An error occurred while updating the post.', 'error')

    return render_template('post/update_post.html', form=form, post=post)



@post.route('/delete/<int:post_id>')
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post:
        if post.post_img:
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], current_user.email, post.post_img)
            os.remove(image_path)
        try:
            db.session.delete(post)
            db.session.commit()

            flash('Your post has been removed successfully!')
            return redirect(url_for('main.home'))
        except:
            flash('Something went wrong please try again')
            return redirect(url_for('main.home'))

app/templates/post/create_post.html
{% extends 'base.html' %}
{% block head %}
    <title>Create Post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/create-post.css') }}">
{% endblock head %}
{% block content %}
    <div class="create-post-container">
        <h1 class="create-post-heading">Create Post</h1>
        {% with err_msg=get_flashed_messages() %}
            {% if err_msg %}
            <ul>
                {% for msg in err_msg %}
                    <li>{{ msg }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}
        <form action="{{ url_for('post.create_post') }}" method="post" enctype="multipart/form-data" class="create-post-form">
            {{ form.csrf_token }}
            <p class="form-field">
                {{ form.content }}
                {% for error in form.content.errors %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>
            <p class="form-field">
                {{ form.image }}<br>
                {% for error in form.image.errors %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>
            <p class="form-field">
                {{ form.create(value='Create Post', class='create-post-submit') }}
            </p>
        </form>
    </div>
{% endblock content %}

app/templates/post/post_detail.html
{% extends 'base.html' %}

{% block head %}
    <title>Detail View</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail-view.css') }}">
{% endblock %}

{% block content %}
    <div class="detail-view-container">
        <div class="post-header">
            <h3 class="post-author">{{ post.user.username }} {{ post.user.last_name }}</h3>
            {% if current_user.id == post.user.id %}
                <div class="edit-post-links">
                    <a href="{{ url_for('post.update_post', post_id=post.id) }}" class="edit-link">Edit</a>
                    <a href="{{ url_for('post.delete_post', post_id=post.id) }}" class="delete-link">Delete</a>
                </div>
            {% endif %}
        </div>
        
        <div class="post-content">
            <p>{{ post.content }}</p>
            {% if post.post_img %}
                <img src="{{ url_for('static', filename='data/' + post.user.email + '/' + post.post_img) }}" alt="My Image" class="post-image">
            {% endif %}
        </div>
        
        <div class="post-interactions">
            <form action="{{ url_for('post.comment', post_id=post.id) }}" method="POST" class="comment-form">
                {{ form.csrf_token }}
                {{ form.content(placeholder='Add a comment', class='comment-input') }}
                {{ form.create(class='comment-submit') }}
            </form>
            
            {% if comments %}
                <div class="comments">
                    <h4 class="comments-heading">Comments</h4>
                    {% for comment in comments %}
                        <div class="comment">
                            <h5 class="comment-author">{{ comment.user.username }} {{ comment.user.last_name }}</h5>
                            <p class="comment-content">{{ comment.content }} {{ comment.created_at }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            
            {% if likes %}
                <div class="likes">
                    <h4 class="likes-heading">Liked by</h4>
                    {% for like in likes %}
                        <p class="like-author">{{ like.user.username }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/post/update_post.html
<!-- template.html -->
{% extends 'base.html' %}

{% block head %}
    <title>Update</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock head %}

{% block content %}
    <div class="update-post">
        <h3 class="post-heading">Update Post: "{{ post.content }}"</h3>
        <form action="{{ url_for('post.update_post', post_id=post.id) }}" method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="content">Content:</label>
                {{ form.content }}
                <ul class="error-list">
                    {% for error in form.content.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                {{ form.image }}
                <ul class="error-list">
                    {% for error in form.image.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {{ form.update }}
        </form>
    </div>
{% endblock content %}