app/friend/__init__.py
from flask import Blueprint

friend  = Blueprint('friend', __name__ )
from . import routes

app/friend/routes.py
from . import friend
from flask_login import current_user, login_required
from app.models import FriendRequest, User, FriendList
from app import db
from flask import redirect, url_for, flash, render_template, abort, jsonify, request
from sqlalchemy.exc import IntegrityError, OperationalError, SQLAlchemyError
from sqlalchemy import and_


@friend.route('/friends')
@login_required
def friends_list():
    # Return friends list of current user
    friends_list = current_user.friends
    return render_template('friend/friends_list.html', friends_list=friends_list)


@friend.route('/friend/requests')
@login_required
def friend_requests():
    frieds_request_list = current_user.friends_request
    list_of_users       = User.query.filter(User.id != current_user.id).all()
    return render_template('friend/friend_requests.html', friends_list=frieds_request_list, users_list=list_of_users)

@friend.route('/friend/add/<int:friend_id>')
@login_required
def send_friend_request(friend_id):
    user = User.query.get_or_404(friend_id)
    if user in current_user.friends:
        flash(f"{user.username} is Already a friend of you in Abook ofc hehe.")
        return redirect(url_for('main.home'))
    elif user:
        friend = FriendRequest(user_id=friend_id, friend_id=current_user.id)
        try:
            db.session.add(friend)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            flash(f'You have already sent a friend request to {user.username}!')
            return redirect(url_for('main.home'))
    flash('Friend request sent successfully!')
    return redirect(url_for('main.home'))

@friend.route('/friend/requests/delete/<int:friend_id>')
@login_required
def delete_friend_request(friend_id):
    friend = FriendRequest.query.filter_by(friend_id=friend_id).first()
    user   = User.query.get_or_404(friend_id)
    if friend and user:
        
        try:
            db.session.delete(friend)
            db.session.commit()
            flash(f'{user.username} has been removed successfully from your friend requests.')
        except IntegrityError:
            db.session.rollback()
            flash(f'Something went wrong while deleting {user.username} from your friend requests!')
        except OperationalError:
            db.session.rollback()
            flash('An unexpected error occurred. Please try again later.')
    else:
        abort(404, "Friend is not found!")

    return redirect(url_for('main.home'))

@friend.route('/friend/accept/<int:friend_id>')
@login_required
def accept_friend_request(friend_id):
    friend_req = FriendRequest.query.filter_by(friend_id=friend_id).first()
    friend = User.query.get_or_404(friend_id)
    
    
    if friend_req and friend:
        friend_user  = FriendList.query.filter(and_(FriendList.friend_id == current_user.id, FriendList.user_id == friend_id)).first()
        if friend in current_user.friends or friend_user:
            flash(f"{friend.username} is already in your friends list")
            db.session.delete(friend_req)
            db.session.commit()

        else:
            # to avoid all the confusing
            acc_fr = FriendList(user_id=current_user.id, friend_id=friend.id)
            acc2_fr= FriendList(user_id=friend.id, friend_id=current_user.id)
            try:
                db.session.add(acc_fr)
                db.session.add(acc2_fr)
                db.session.delete(friend_req)
                db.session.commit()
                flash(f"{friend.username} is your friend now!")
            except Exception as e:
                db.session.rollback()
                flash(f"Error: {str(e)}")
    else:
        abort(404)

    return redirect(url_for('friend.friend_requests'))


# Delete a friend 
@friend.route('/friend/delete/<int:friend_id>')
@login_required
def delete_friend(friend_id):
    # check if the friend does exits as a user
    friend = User.query.get_or_404(friend_id)
    # check if the friend is in the current_user friends lists
    if friend and friend in current_user.friends:
        fr_col_1 = FriendList.query.filter(and_(FriendList.friend_id==friend_id, FriendList.user_id==current_user.id)).first()
        # Get the sec column of the friend ship
        fr_col_2 = FriendList.query.filter(and_(FriendList.friend_id==current_user.id, FriendList.user_id==friend_id)).first()
        # delete the friendship 
        try:
            db.session.delete(fr_col_1)
            db.session.delete(fr_col_2)
            db.session.commit()
            flash(f"You have unfraind {friend.username}.")
        except SQLAlchemyError as e:
             db.session.rollback()
             flash(f"Error occurred while deleting the friend: {str(e)}")
            
    return redirect(url_for('friend.friends_list'))

app/templates/friend/friend_requests.html
{% extends 'base.html' %}

{% block head %}
<title>Friend Requests</title>
{% endblock head %}

{% block content %}
    <div class='errors'>
        {% with err_msg=get_flashed_messages()  %}
            {% if err_msg %}
                <ul>
                    {% for msg in err_msg %}
                        <li>{{ msg }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
    </div>
    <div class="friend-requests">
        <a href="{{ url_for('friend.friends_list') }}">Friends</a>
        {% if friends_list %}
            <h1>Friend requests</h1>
            <div class="friend-container">
                {% for friend in friends_list %}
                    <div class="friend-card">
                        <div class="profile-picture">
                            {% if friend.profile_pic %} 
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='data/' + friend.email + '/' + friend.profile_pic) }}" alt="Profile Picture">
                                </a>
                            {% else %}
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
                                </a>
                            {% endif %}
                        </div>
                        <div class="username">
                            <h2>{{ friend.username }}</h2>
                        </div>
                        <div class="buttons">
                            <a href="{{ url_for('friend.accept_friend_request', friend_id=friend.id) }}">
                                <button class="accept-btn" >Accept</button>
                            </a>
                            <a href="{{ url_for('friend.delete_friend_request', friend_id=friend.id) }}">
                                <button class="delete-btn" >Delete</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="no-requests">No friend requests at the moment.</p>
        {% endif %}
    </div>
    <div class="users-container">
        {% if users_list %}
        <h1>Users You might now!</h1>
            <div class="user-container">
                {% for user in users_list %}
                    <div class="user-card">
                        <div class="profile-picture">
                            {% if user.profile_pic %} 
                                <a href="{{ url_for('profiles.user_profile', user_id=user.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='data/' + user.email + '/' + user.profile_pic) }}" alt="Profile Picture">
                                </a>
                            {% else %}
                                <a href="{{ url_for('profiles.user_profile', user_id=user.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
                                </a>
                            {% endif %}
                        </div>
                        <div class="username">
                            <h3>{{ user.username }}</h3>
                        </div>
                        <div class="buttons">
                            <a href="{{ url_for('friend.send_friend_request', friend_id=user.id) }}">
                              
                                <button class="accept-btn" >Add</button>
                            </a>
            
                            <a href="{{ url_for('profiles.user_profile', user_id=user.id) }}">
                                
                                <button class="success-btn" >View Profile</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock content %}

app/templates/friend/friends_list.html
{% extends 'base.html' %}

{% block head %}
    <title>Friend Requests</title>
{% endblock head %}

{% block content %}
    <div class='errors'>
        {% with err_msg=get_flashed_messages()  %}
            {% if err_msg %}
                <ul>
                    {% for msg in err_msg %}
                        <li>{{ msg }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
    </div>
    <div class="friend-requests">
        {% if friends_list %}
            <div class="friend-container">
                {% for friend in friends_list %}
                    <div class="friend-card">
                        <div class="profile-picture">
                            {% if friend.profile_pic %} 
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='data/' + friend.email + '/' + friend.profile_pic) }}" alt="Profile Picture">
                                <a>
                            {% else %}
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <!--default image-->
                                    <img class="profile-pic" src="{{ url_for('static', filename='images/defaul_image.jpeg') }}" alt="Default Profile Picture">
                                </a>
                            {% endif %}
                        </div>
                        <div class="username">
                            <h3>{{ friend.username }} {{ friend.last_name }}</h3>
                        </div>
                        <div class="buttons">
                            <a href="#">
                                <button class="accept-btn">Message</button>
                            </a>
                            <a href="{{ url_for('friend.delete_friend', friend_id=friend.id) }}">
                                <button class="delete-btn">Unfraind</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="no-requests">Find your friends! <a href="{{ url_for('friend.friend_requests') }}">Here</a></p>
        {% endif %}
    </div>
{% endblock content %}

app/templates/friend/request_friends.html
{% extends 'base.html' %}

{% block head %}
    <title>Friend Requests</title>
{% endblock head %}

{% block content %}
    <div class="friend-requests">
        {% if friends_list %}
            <div class="friend-container">
                {% for friend in friends_list %}
                    <div class="friend-card">
                        <div class="profile-picture">
                            {% if friend.profile_pic %} 
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='data/' + friend.email + '/' + friend.profile_pic) }}" alt="Profile Picture">
                                </a>
                            {% else %}
                                <a href="{{ url_for('profiles.user_profile', user_id=friend.id) }}">
                                    <img class="profile-pic" src="{{ url_for('static', filename='images/default_image.jpeg') }}" alt="Default Profile Picture">
                                </a>
                            {% endif %}
                        </div>
                        <div class="username">
                            <h3>{{ friend.first_name }} {{ friend.last_name }}</h3>
                        </div>
                        <div class="buttons">
                            <button class="accept-btn" onclick="Accept('{{ friend.id }}', 'accept')">Accept</button>
                            <button class="delete-btn" onclick="Delete('{{ friend.id }}', 'delete')">Delete</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="no-requests">No friend requests at the moment.</p>
        {% endif %}
    </div>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock content %}